### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by annasindhu** [SagarMaheshwary/Employee#1]
I am using Xampp. i installed correctly but aftergiving the username and password loging page is not responding.Validation is working

**Comment by SagarMaheshwary** [comment]
Please give me a screenshot of your error.

**Comment by annasindhu** [comment]
![image](https://user-images.githubusercontent.com/34735237/49279583-e8612400-f4ad-11e8-8da0-f9682cdf087c.png)

**Comment by annasindhu** [comment]
after pressing the LOGINBUTTON no action happened in the projects no error is showing

**Comment by SagarMaheshwary** [comment]
This project is built on materialize-css, so please use a better browser like chrome.

**Comment by annasindhu** [comment]
i checked with opera and crome but no change

**Comment by SagarMaheshwary** [comment]
Is the login form submitting?

**Comment by annasindhu** [comment]
values are passing but
![image](https://user-images.githubusercontent.com/34735237/49281964-f3b74e00-f4b3-11e8-9ef4-407376a1c2c3.png)

**Comment by SagarMaheshwary** [comment]
I have tested the login just now but I didn't see a problem. I think you might have missed a step. Check if you have correctly setup the database configurations and please enable php errors.

**Comment by SagarMaheshwary** [comment]
Instead of using apache, open you cmd, cd into the project directory and run,
```bash
php artisan serve
```
open the url you see on the cmd and then try login again.

**Comment by annasindhu** [comment]
Thanks for the immediate support ....Its working fine in http://127.0.0.1:8000/dashboard but not in apache
do you know why it happen

**Comment by SagarMaheshwary** [comment]
The public directory contains the **index.php** file, which is the entry point for all requests entering your application. So, when you login, you get redirected to **localhost/dashboard** instead of **localhost/your-laravel-project/public/dashboard**. For these cases you can use a virtual host. Here's an example [https://stackoverflow.com/a/36572751](url) or you can google it for better examples.

**Comment by annasindhu** [comment]
Hi i understood the problem,in apache after login-> page submitting in http://localhost/projectname/dashboard  instead of  http://127.0.0.1:8000/dashboard thats the problem 
is there any possiblelity to change the path in the Employee-master project.

**Comment by SagarMaheshwary** [comment]
https://github.com/SagarMaheshwary/Employee/issues/9
