### ISSUE TITLE
NO_AUTO_CREATE_USER

### ISSUE THREAD

**Issue by arthurkay** [SagarMaheshwary/Employee#10]
Hi,

I am using PHP 7.3
MySQL V8.0.20

And I am getting the following error.

PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1231 Variable 'sql_mode' can't be set to the value of 'NO_AUTO_CREATE_USER'")

After searching the internet, I found a solution to this issue, which is to deliberately ignore the 'NO_AUTO_CREATE_USER' in Laravel.

More info about this can be found here:

https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sql-mode-full

**Comment by arthurkay** [comment]
I have a solution to the above, what are the conditions to submit a PR?

**Comment by SagarMaheshwary** [comment]
There aren't any specific conditions for the pull request. Just commit changes and create a pull request. I will review your pull request before merging those changes.

**Comment by arthurkay** [comment]
Sorry, I only realised today that you had responded and agreed that I make a PR.
