### ISSUE TITLE
+

### ISSUE THREAD

**Issue by me10071990** [SagarMaheshwary/Employee#3]
C:\xampp\htdocs\Employee-master.. this is my file source

**Comment by me10071990** [comment]
Please help with steps

**Comment by me10071990** [comment]
Hello sir, how are you. Can I ask something?

**Comment by SagarMaheshwary** [comment]
Yes!

**Comment by me10071990** [comment]
Is the laravel is thought to learn and implement only 4 commands insert
delete update view?

**Comment by me10071990** [comment]
You know I am trying to do my best, even I have visited your link but there
is not any clarification. How first create HTML page at which secretion and
then fetch data from data base and show in table in homepage. Like you did.

**Comment by SagarMaheshwary** [comment]
You can do a lot more than just CRUD ( Create Read Update Delete) operations. Read the Laravel [docs](laravel.com)

**Comment by SagarMaheshwary** [comment]
First watch the entire series and then start building your own app.

**Comment by me10071990** [comment]
I have gone through it sir, but somewhere getting confusion, so I just
asked you to learn and make simple page where I can modify data.


Is it possible to you, for make step by step process for insert , delete ,
edit in a simple page. Please help if you can.

**Comment by SagarMaheshwary** [comment]
Laravel is an MVC (Model View Controller) framework.
Views will be the User Interface (what you see).
Models will interact with the database (to query and fetch data).
Controller will contain the logic like validation and storing data to the database.
Extra: Template engines are used to embed logic inside a view e.g hide the create reviews section if a user is unauthenticated.
I Hope this will get you started!

**Comment by me10071990** [comment]
Yes , sir thank you.

**Comment by SagarMaheshwary** [comment]
You're welcome!

**Comment by me10071990** [comment]
So I have installed the laravel and create project and now I am using PHP
Strom. Where I have made database in .env file.

**Comment by me10071990** [comment]
So after that what I do first create HTML file or what do I have first?

**Comment by SagarMaheshwary** [comment]
I think you should watch that series or find other resources. At first everything is different, so keep trying until you understand.

**Comment by me10071990** [comment]
I was doing, even go through another resources, but they never mention that
for a simple update delete and edit , which steps we have to follow.

Please help me with steps for it. Thank you sir.

**Comment by SagarMaheshwary** [comment]
I'm writing a tutorial series on Laravel basics with materialize-css. I may take a day or two to complete. When it's complete I will notify you on this issue.

**Comment by me10071990** [comment]
It's very nice sir, and please mentioned a procedure to follow for a demo
website where we can insert delete and update data with data base like you
made your ems not fully just demo website,  I read many but never has
mentioned. Please add lecture video on udemy soon.

I will wait for your update notifications.

Very appericable. Thank you very much. Best of luck.

**Comment by me10071990** [comment]
hello sir, how are you?

**Comment by SagarMaheshwary** [comment]
I will get the tutorials done by tomorrow. I have published one tutorial, you can read it [here](https://sagarmaheshwary.herokuapp.com/posts/Laravel-Blog-with-Materialize-css:-Intro-and-Set-up). Please don't share this website with anyone because it will be gone in 1 or 2 weeks. I will notify you when the production site is ready.

**Comment by SagarMaheshwary** [comment]
Here's the demo laravel app where you can create, read, update, and delete posts. Url: [here](https://warm-ravine-35968.herokuapp.com) and the source code is [here](https://github.com/SagarMaheshwary/laravel-basics/tree/a2ab6289e474238f90c65cc1cb78fc71d658da31). This repo is available in this account named as Laravel-basics.

**Comment by me10071990** [comment]
Thank you so much sir

**Comment by SagarMaheshwary** [comment]
Glad to help you. Feel free to contact me if you find the tutorials hard. I will soon add the authentication tutorial.

**Comment by me10071990** [comment]
Ok sir

**Comment by me10071990** [comment]
Wish you and your family a very happy new Year.

**Comment by SagarMaheshwary** [comment]
Happy new year to you too!

**Comment by me10071990** [comment]
I am happy to inform you that I have used your steps to learn laravel and
do codes and it has been done by me very successful. Thanks again.

**Comment by SagarMaheshwary** [comment]
That's great to hear! I hope you will continue to work hard.

**Comment by me10071990** [comment]
Yes, Thank you. I am doing very well, I have started simple project few
days ago and it's working fine. One thing I wanted to know , if I will make
a admin section and wanted to merge this section and give announcement bon
home page for all user.

**Comment by SagarMaheshwary** [comment]
Do you want to send notifications to all users?

**Comment by me10071990** [comment]
So this announcement should be appears on home page in specific tab so when
user will login in site so can see notification

**Comment by me10071990** [comment]
Yes

**Comment by SagarMaheshwary** [comment]
You can use laravel [notifications](https://laravel.com/docs/5.7/notifications) to implement that.

**Comment by SagarMaheshwary** [comment]
With Laravel notifications you can email all the users or sms them as well as store them to the database so they can see all the notification on their dashboard.

**Comment by me10071990** [comment]
Yes I tried to do this by this link, but it's too vast to understand.

**Comment by me10071990** [comment]
Thanks, so how I have to go through it, bu step

**Comment by SagarMaheshwary** [comment]
you can start from this youtube [video](https://www.youtube.com/watch?v=apvyhvaD4lo).

**Comment by me10071990** [comment]
Thanks

**Comment by SagarMaheshwary** [comment]
You're welcome!

**Comment by me10071990** [comment]
Hi Sir

**Comment by me10071990** [comment]
Hello Sir, First  Thank you very much for your awesome teaching standard. I
am following the same AND this is very useful for me.


I want apply new concept in this blog page.

I want to display a current weather information in  this blog, first i want
make a panel and want shows report of weather(in 3 section one for current
or today date, 2nd for yesterday and 3rd is for day before yesterday).

Please help me in this so i can learn and also can implement, Please help
me with step by step so I can learn in better way

**Comment by SagarMaheshwary** [comment]
you can use a weather api to get the data. though I have never used any but you can search it on the internet.

**Comment by me10071990** [comment]
I searched but getting something odd

**Comment by SagarMaheshwary** [comment]
there is this package in php: https://github.com/cmfcmf/OpenWeatherMap-PHP-Api. If you try then you can do it.

**Comment by me10071990** [comment]
Thank you very much, I will try and try to complete

**Comment by SagarMaheshwary** [comment]
Good luck!
