### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by me10071990** [SagarMaheshwary/Employee#4]
C:\xampp\Employee-master\Employee-master>php artisan migrate
PHP Warning:  require(C:\xampp\Employee-master\Employee-master/vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\Employee-master\Employee-master\artisan
on line 18

Warning: require(C:\xampp\Employee-master\Employee-master/vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\Employee-master\Employee-master\artisan on li
ne 18
PHP Fatal error:  require(): Failed opening required 'C:\xampp\Employee-master\Employee-master/vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\Employee-master\Employe
e-master\artisan on line 18

Fatal error: require(): Failed opening required 'C:\xampp\Employee-master\Employee-master/vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\Employee-master\Employee-mas
ter\artisan on line 18

**Comment by SagarMaheshwary** [comment]
It seems like you did not run **composer install** command. Go to **employee-master** and see if you have a **vendor** folder

**Comment by me10071990** [comment]
I set up all and able to go on login page
But email address and password is not working

**Comment by SagarMaheshwary** [comment]
did you run the db:seed command which will create the admin user in users table:
```bash
php artisan db:seed
```

**Comment by me10071990** [comment]
Yes I did

**Comment by SagarMaheshwary** [comment]
Are you getting a validation error? Please add a screen shot.

**Comment by me10071990** [comment]
Sir, you are really good programmer and nice man, really appeaicable. Why
you not starting your class in udemy. Here you can start and your course
will help to learn step by step all things for every student.

**Comment by me10071990** [comment]
Getting nothing.

**Comment by SagarMaheshwary** [comment]
Thanks for your concern but I'm unable to do that, may be in future. anyways, give me a screenshot of your login page.

**Comment by me10071990** [comment]
Ok sir

**Comment by me10071990** [comment]
[image: image.png]

**Comment by SagarMaheshwary** [comment]
https://github.com/SagarMaheshwary/Employee/issues/1
read this issue maybe you are having the same problem.

**Comment by me10071990** [comment]
Still checking all info thank you, by the way, where are you from

**Comment by SagarMaheshwary** [comment]
My friend Github issue is not for personal chat. Just look at my github profile and you will know where I'm from.

**Comment by me10071990** [comment]
Nice sir.

**Comment by me10071990** [comment]
so can i get some classes from you about laravel, how to create delete
insert information in admin page with database.

I will request you to please start your classes on Udemy so student can pay
you there and can know all procedure step by step.

Thank you.

**Comment by SagarMaheshwary** [comment]
Right now I can't do that but I will be writing tutorials on medium.

**Comment by me10071990** [comment]
Ok sir, and also can you provide me laravel classes  for making simple
insert delete update with database in admin page .

**Comment by SagarMaheshwary** [comment]
https://www.youtube.com/watch?v=EU7PRmCpx-0&list=PLillGF-RfqbYhQsN5WMXy6VsDMKGadrJ-
use this series to learn laravel.

**Comment by me10071990** [comment]
Thank you very much

**Comment by me10071990** [comment]
still i am not able to login on that page can you check through teamviewer
please

**Comment by me10071990** [comment]
Now showing credentials are wrong

**Comment by me10071990** [comment]
finally its working now
