### ISSUE TITLE
Hi i understood the problem,in apache after login-> page submitting in http://localhost/projectname/dashboard  instead of  http://127.0.0.1:8000/dashboard thats the problem

### ISSUE THREAD

**Issue by annasindhu** [SagarMaheshwary/Employee#5]
is there any possibility to change the path in the Employee-master project.

_Originally posted by @annasindhu in https://github.com/SagarMaheshwary/Employee/issues/1#issuecomment-443596033_

**Comment by SagarMaheshwary** [comment]
Please read about virtual hosts in apache.
