### ISSUE TITLE
Object not found!

### ISSUE THREAD

**Issue by sprikitik** [SagarMaheshwary/Employee#9]
Good day sir!
I cant seem to click employee, system and admin management.
Please help. Thanks.

![image](https://user-images.githubusercontent.com/58059068/69395500-22a87e80-0d1a-11ea-9f87-bb211d2cd6bc.png)

**Comment by SagarMaheshwary** [comment]
Read this comment: https://github.com/SagarMaheshwary/Employee/issues/1#issuecomment-443188607

**Comment by SagarMaheshwary** [comment]
if you need any help then feel free to ask!
